name: squad
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ujson
  - numpy
  - pip
  - spacy=2.0.16
  - tensorboard=1.15.0
  - tqdm
  - urllib3
  - pytorch=1.7
  - black
  - pip:
    - torchinfo
